spring.application.name=finance

spring.datasource.url=jdbc:postgresql://dpg-d79nietm5p6s73a6dgb0-a:5432/finance_db_kazx
spring.datasource.username=finance_db_kazx_user
spring.datasource.password=r8nTAZRQbTBt3N49cRs5GHA3ARaGsEaC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
